config/routes.rb
Rails.application.routes.draw do
  root 'tracks#index'
  resources :tracks
  match 'tracks/audio_download/:id', to: 'tracks#audio_download', via: :get, as: :audio_download
  Track.all.each do |track|
    get "/system/tracks/audios/000/000/00#{track.id}/original/#{track.audio_file_name}", to: "tracks#path_to_track"
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_attached_file :audio
  validates :title, :artiste, presence: true
  validates_attachment_presence :audio
  validates_attachment_content_type :audio, content_type: [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :find_track, only: [:edit, :destroy, :update, :audio_download, :stream, :path_to_track]

  def index
    @tracks = Track.all
  end

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to tracks_path, notice: 'The track has been successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @track.update_attributes(track_params)
      redirect_to tracks_path, notice: "'#{@track.title}' has been successfully updated"
    else
      render :edit
    end
  end

  def audio_download
    file_path = @track.audio_file_name
    if file_path.present?
      send_file path_to_track,
                filename: @track.audio_file_name,
                type: @track.audio_content_type,
                disposition: 'attachment'
    end
  end

  def path_to_track
    file_path = @track.audio_file_name
    send_file "#{Rails.root}/public/system/tracks/audios/000/000/00#{@track.id}/original/#{file_path}"
  end

  def destroy
    @track.destroy
    redirect_to tracks_path, notice: "The track has been successfully deleted"
  end

  private

  def track_params
    params.require(:track).permit(:title, :artiste, :audio)
  end

  def find_track
    @track = Track.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MicroPlaylist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/messages' %>
<%= yield %>
</body>
</html>

app/views/shared/_messages.html.erb
<% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "alert alert-message" %>
<% end %>

app/views/tracks/_form.html.erb
<% if @track.new_record? %>
    New Track
<% else %>
    Edit Track
<% end %>

<%= form_for @track do |f| %>

    <% @track.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
    <% end %>
<%# end %>

    <p>
      <%= f.label :artiste %>
    <p><%= f.text_field :artiste %></p>
    </p>

    <p>
      <%= f.label :title %>
      <p><%= f.text_field :title %></p>
    </p>

    <p>
      <%= f.label :audio %>
      <p><%= f.file_field :audio %></p>
    </p>

    <%= f.submit "Save", button_html: {data: {disable_with: 'Please wait...'}} %>
<% end %>

<p>Go back <%= link_to 'Home', root_path %></p>

app/views/tracks/_track.html.erb
<%= content_tag_for :tr, track do %>
    <% track_route = "/system/tracks/audios/000/000/00#{track.id}/original/#{track.audio_file_name}" %>
    <td><%= track.artiste %></td>
    <td><%= track.title %></td>
    <td><%= track.audio_file_name %></td>
    <td>
      <audio id="<%= track.id %>" controls>
        <source src=<%=track_route%>>
      </audio>

      <%= link_to 'Download', audio_download_path(track), method: :get %>
      <%= link_to 'Edit', edit_track_path(track) %>
      <%= link_to 'Delete', track, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
<% end %>

app/views/tracks/edit.html.erb
<%= render 'form' %>

app/views/tracks/index.html.erb
<h3>Tracks</h3>
<p><%= link_to 'Create a New Track', new_track_path %></p>

<% if @tracks.present? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Artiste</th>
          <th>Title</th>
          <th>Audio</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%= render @tracks %>
      </tbody>
    </table>
<% else %>
    <em>There are no tracks available</em>
<% end %>

app/views/tracks/new.html.erb
<%= render 'form' %>